import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const A='/assets/';
const agents=[
  {name:'Campaign Reporting Agent',application:'Salesforce',scope:'Write',permission:'Allow',why:'Sensitive action can run without approval'},
  {name:'Campaign Operations Agent',application:'HubSpot',scope:'Write',permission:'Allow',why:'Campaign changes can run without review'},
  {name:'Lead Routing Agent',application:'Salesforce',scope:'Write',permission:'Allow',why:'Lead ownership can change without approval'},
];
const suggestions=[
  ['Harden agent access','Review agent permissions, application access, and authentication policies'],
  ['Review agent permissions','Inspect agent permissions and identify unnecessary access'],
  ['Review agent application access','Review which applications agents can access'],
  ['Strengthen authentication','Review authentication paths and enforce stronger policies'],
  ['Review unmanaged access','Identify access to applications outside approved policies'],
];
const recommendations=[
  ['imgAccessAndPermissionsKeyIcon.svg','Local Accounts Bypassing NewCore Policies','6 Local Accounts Access Apps Without Passing Through NewCore Policies'],
  ['imgApplicationsIcon1.svg','Agents accessing unmanaged apps','2 agents are accessing discovered apps that were never approved'],
  ['imgAuthenticationIcon.svg','Weak authentication paths','4 policies allow agents to authenticate through weaker paths'],
];
function Icon({file,className=''}){return <img className={'icon '+className} alt="" src={A+file}/>}
function Header(){return <header className="topbar"><img className="brand" src={A+'logo.svg'} alt="newcore"/><div className="account"><Icon file="imgAvatar.svg"/><span>Aven Stroud</span><span className="chev down"/></div></header>}
function Sidebar(){return <aside className="sidebar"><nav><div className="nav-active"><Icon file="imgGitBranch.svg"/>Action Center</div><div className="nav-divider"/>{[['imgIdentitiesIcon.svg','Identities'],['imgAgentsIcon.svg','Agents'],['imgApplicationsIcon.svg','Applications'],['imgPoliciesIcon.svg','Policies']].map(([icon,label])=><div className="nav-item" key={label}><Icon file={icon}/>{label}</div>)}</nav></aside>}
function App(){
  const [stage,setStage]=useState('home');const [query,setQuery]=useState('');const [searchOpen,setSearchOpen]=useState(false);const [scope,setScope]=useState(false);const [scopeQuery,setScopeQuery]=useState('');const [expanded,setExpanded]=useState(false);const [selected,setSelected]=useState([]);const [modal,setModal]=useState(false);
  const allSelected=selected.length===agents.length;
  const matchesHardenAgentAccess=query.trim().length>0&&'harden agent access'.startsWith(query.trim().toLowerCase());
  useEffect(()=>{const key=e=>{if(e.key==='Escape'){if(modal)setModal(false);else setSearchOpen(false)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[modal]);
  const chooseAction=()=>{setStage('scope');setSearchOpen(false);setQuery('Harden agent access')};
  const back=()=>{setStage('home');setQuery('');setExpanded(false);setSelected([]);setScope(false)};
  const toggle=name=>setSelected(s=>s.includes(name)?s.filter(x=>x!==name):[...s,name]);
  return <div className="app"><Header/><Sidebar/><main className={stage==='results'||stage==='success'?'main results-main':'main'}>
    {stage==='home'||stage==='scope'?<div className="home-content">
      <div className="page-heading"><h1>Action Center</h1><p>Investigate and act across identities, agents, apps, and policies</p></div>
      <div className="tabs"><button className="tab active">Actions</button><button className="tab">Activity</button></div>
      <div className="search-wrap"><div className={'searchbox '+(searchOpen||stage==='scope'?'focused':'')}><input aria-label="Search actions" placeholder="Search actions or describe what you want to accomplish" value={query} onFocus={()=>{if(stage==='home')setSearchOpen(true)}} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} onKeyDown={e=>{if(e.key==='Enter'&&query.trim())chooseAction()}}/><span className="magnify"/></div>
        {stage==='home'&&searchOpen&&<div className="popover search-popover">{query.trim()?<>{matchesHardenAgentAccess&&<><div className="popover-title">Matching actions</div><button className="suggestion" onClick={chooseAction}><strong>Harden agent access</strong><span>Review agent permissions, application access, and authentication policies</span></button></>}<button className="continue" onClick={chooseAction}>Continue with your request <span>→</span></button></>:<><div className="popover-title">Actions</div><div className="filters">{['All','Agents','Identities','Apps','Policies'].map((f,i)=><span className={i===0?'filter-current':''} key={f}>{f}</span>)}</div>{suggestions.map(([title,desc])=><button className="suggestion" key={title} onClick={chooseAction}><strong>{title}</strong><span>{desc}</span></button>)}<button className="browse" onClick={chooseAction}>Browse all actions</button></>}</div>}
        {stage==='scope'&&<div className="popover scope-popover"><h2>Who should this apply to?</h2><input className="scope-input" placeholder="Search teams, people, or agents" aria-label="Search scope" value={scopeQuery} onChange={e=>setScopeQuery(e.target.value)}/>{'marketing'.includes(scopeQuery.toLowerCase())&&<button className={'scope-choice '+(scope?'chosen':'')} onClick={()=>setScope(true)}><strong>Marketing</strong><span>Team · 12 agents</span>{scope&&<b>✓</b>}</button>}<div className="scope-bottom"><div><strong>Selected</strong><span>{scope?'Marketing · 12 agents':'None'}</span></div><button className="pill black" disabled={!scope} onClick={()=>setStage('results')}>Investigate</button></div></div>}
      </div>
      <section className="recommendations"><h2>Recommended for you</h2><p>Suggested actions based on risks identified in your environment</p>{recommendations.map(([icon,title,desc])=><button className="recommendation" key={title} onClick={()=>{setSearchOpen(true);setQuery('')}}><Icon file={icon}/><span className="recommend-text"><strong>{title}</strong><small>{desc}</small></span><span className="recommend-link">Investigate →</span></button>)}</section>
    </div>:stage==='results'?<><div className="result-heading"><h1>Harden marketing agent access</h1><p>Review the findings before making any changes</p><div className="scope-value">Marketing · 12 agents</div></div><section className="results-card"><h2>Investigation results</h2><p className="results-sub">We identified risks across permissions, application access, and authentication</p><div className="column-head"><span>Finding</span><span>Recommended change</span></div><div className="finding"><button className="finding-top" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><Icon file="imgAccessAndPermissionsKeyIcon.svg"/><span className="finding-name"><strong>Sensitive write actions without approval</strong><small>3 agents</small></span><span className="finding-action"><strong>Require approval for sensitive write actions</strong><small>Allow&nbsp; → &nbsp;<b>Ask</b></small></span><span className={'chev '+(expanded?'up':'down')}/></button>{expanded&&<div className="affected"><h3>Affected agents</h3><div className="agent-table"><div className="agent-row agent-header"><input type="checkbox" aria-label="Select all affected agents" checked={allSelected} onChange={e=>setSelected(e.target.checked?agents.map(a=>a.name):[])}/><strong>Agent</strong><strong>Application</strong><strong>Scope</strong><strong>Permission</strong><strong>Why it matters</strong></div>{agents.map(a=><label className="agent-row" key={a.name}><input type="checkbox" aria-label={'Select '+a.name} checked={selected.includes(a.name)} onChange={()=>toggle(a.name)}/><span>{a.name}</span><span>{a.application}</span><span>{a.scope}</span><span>{a.permission}</span><span title={a.why}>{a.why}</span></label>)}</div></div>}</div><div className="finding"><div className="finding-top static"><Icon file="imgApplicationsIcon1.svg"/><span className="finding-name"><strong>Access to unmanaged applications</strong><small>2 agents</small></span><span className="finding-action"><strong>Review unmanaged application access</strong></span><span className="chev down"/></div></div><div className="finding"><div className="finding-top static"><Icon file="imgAuthenticationIcon.svg"/><span className="finding-name"><strong>Weak authentication paths</strong><small>4 agents</small></span><span className="finding-action"><strong>Strengthen authentication requirements</strong></span><span className="chev down"/></div></div></section><div className="bottom-bar"><button className="pill outline" onClick={back}>← Back to actions</button><button className="pill black apply" disabled={!allSelected} onClick={()=>setModal(true)}>Apply changes</button></div></>:<div className="success"><div className="success-mark">✓</div><h1>Changes applied</h1><p>Approval is now required for sensitive write actions by the three selected marketing agents.</p><button className="pill black" onClick={back}>Back to Action Center</button></div>}
  </main>{modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" aria-label="Close dialog" onClick={()=>setModal(false)}>×</button><div className="modal-body"><h2 id="modal-title">Apply changes?</h2><p>Review the selected changes before applying them.</p><div className="change-summary"><strong>Require approval for sensitive write actions</strong><span>Permission change: &nbsp;Allow&nbsp; → &nbsp;<b>Ask</b></span></div><h3>3 agents affected</h3>{agents.map(a=><div className="modal-agent" key={a.name}>{a.name}</div>)}</div><div className="modal-footer"><button className="pill outline" onClick={()=>setModal(false)}>Cancel</button><button className="pill black" onClick={()=>{setModal(false);setStage('success')}}>Confirm &amp; apply</button></div></div></div>}</div>
}

createRoot(document.getElementById('root')).render(<App/>);
